
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package SintexAnalysis;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int ERRO_TAM_MAX_NUMERO = 48;
  public static final int NUMERO = 51;
  public static final int ERRO_COMENTARIO_MULT_LINHAS_SEM_FECHAR = 44;
  public static final int RSV_BEGIN = 4;
  public static final int PARENTESES_DIR = 33;
  public static final int DELIMITADOR = 46;
  public static final int OPERADOR_LOGICO_OR = 25;
  public static final int SIMBOLO_VIRGULA = 35;
  public static final int COMENTARIO_MULT_LINHAS = 43;
  public static final int OPERADOR_ARITMETICO_MULTIPLICACAO = 30;
  public static final int ERRO = 50;
  public static final int IDENTIFICADOR = 38;
  public static final int TIPO_BOOLEAN = 17;
  public static final int LETRA = 40;
  public static final int RSV_IF = 6;
  public static final int RSV_END = 5;
  public static final int ERRO_SIMBOLO_INVALIDO = 47;
  public static final int COMENTARIO_UMA_LINHA = 42;
  public static final int ERRO_COMENTARIO_MULT_LINHAS_SEM_ABRIR = 45;
  public static final int RSV_WHILE = 9;
  public static final int RSV_VAR = 13;
  public static final int EOF = 0;
  public static final int ERRO_TAM_MAX_IDENTIFICADOR = 49;
  public static final int SIMBOLO_DOIS_PONTOS = 34;
  public static final int error = 1;
  public static final int DIGITO = 41;
  public static final int RSV_TRUE = 14;
  public static final int RSV_FALSE = 15;
  public static final int TIPO_INT = 16;
  public static final int OPERADOR_ARITMETICO_SUBTRACAO = 29;
  public static final int OPERADOR_ARITMETICO_ADICAO = 28;
  public static final int OPERADOR_LOGICO_NOT = 26;
  public static final int OPERADOR_LOGICO_AND = 24;
  public static final int OPERADOR_LOGICO_DIFERENCA = 18;
  public static final int SIMBOLO_PONTO_E_VIRGULA = 36;
  public static final int RSV_ELSE = 8;
  public static final int PARENTESES_ESQ = 32;
  public static final int RSV_READ = 11;
  public static final int OPERADOR_LOGICO_MENOR_IGUAL = 20;
  public static final int OPERADOR_LOGICO_MAIOR_IGUAL = 21;
  public static final int RSV_THEN = 7;
  public static final int OPERADOR_ARITMETICO_ATRIBUICAO = 27;
  public static final int SIMBOLO_TERMINACAO = 37;
  public static final int RSV_PROGRAMA = 2;
  public static final int RSV_DO = 10;
  public static final int OPERADOR_LOGICO_MAIOR = 22;
  public static final int OPERADOR_ARITMETICO_DIVISAO = 31;
  public static final int NUMERO_INTEIRO = 39;
  public static final int RSV_WRITE = 12;
  public static final int OPERADOR_LOGICO_IGUALDADE = 23;
  public static final int RSV_PROCEDIMENTO = 3;
  public static final int OPERADOR_LOGICO_MENOR = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RSV_PROGRAMA",
  "RSV_PROCEDIMENTO",
  "RSV_BEGIN",
  "RSV_END",
  "RSV_IF",
  "RSV_THEN",
  "RSV_ELSE",
  "RSV_WHILE",
  "RSV_DO",
  "RSV_READ",
  "RSV_WRITE",
  "RSV_VAR",
  "RSV_TRUE",
  "RSV_FALSE",
  "TIPO_INT",
  "TIPO_BOOLEAN",
  "OPERADOR_LOGICO_DIFERENCA",
  "OPERADOR_LOGICO_MENOR",
  "OPERADOR_LOGICO_MENOR_IGUAL",
  "OPERADOR_LOGICO_MAIOR_IGUAL",
  "OPERADOR_LOGICO_MAIOR",
  "OPERADOR_LOGICO_IGUALDADE",
  "OPERADOR_LOGICO_AND",
  "OPERADOR_LOGICO_OR",
  "OPERADOR_LOGICO_NOT",
  "OPERADOR_ARITMETICO_ATRIBUICAO",
  "OPERADOR_ARITMETICO_ADICAO",
  "OPERADOR_ARITMETICO_SUBTRACAO",
  "OPERADOR_ARITMETICO_MULTIPLICACAO",
  "OPERADOR_ARITMETICO_DIVISAO",
  "PARENTESES_ESQ",
  "PARENTESES_DIR",
  "SIMBOLO_DOIS_PONTOS",
  "SIMBOLO_VIRGULA",
  "SIMBOLO_PONTO_E_VIRGULA",
  "SIMBOLO_TERMINACAO",
  "IDENTIFICADOR",
  "NUMERO_INTEIRO",
  "LETRA",
  "DIGITO",
  "COMENTARIO_UMA_LINHA",
  "COMENTARIO_MULT_LINHAS",
  "ERRO_COMENTARIO_MULT_LINHAS_SEM_FECHAR",
  "ERRO_COMENTARIO_MULT_LINHAS_SEM_ABRIR",
  "DELIMITADOR",
  "ERRO_SIMBOLO_INVALIDO",
  "ERRO_TAM_MAX_NUMERO",
  "ERRO_TAM_MAX_IDENTIFICADOR",
  "ERRO",
  "NUMERO"
  };
}

