/* Generated By:JavaCC: Do not edit this line. Scanner_1Constants.java */
package JavaCC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Scanner_1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_UMA_LINHA = 5;
  /** RegularExpression Id. */
  int COMENTARIO_MULT_LINHAS = 6;
  /** RegularExpression Id. */
  int COM = 7;
  /** RegularExpression Id. */
  int NOVA = 8;
  /** RegularExpression Id. */
  int RSV_PROGRAMA = 9;
  /** RegularExpression Id. */
  int RSV_PROCEDIMENTO = 10;
  /** RegularExpression Id. */
  int RSV_BEGIN = 11;
  /** RegularExpression Id. */
  int RSV_END = 12;
  /** RegularExpression Id. */
  int RSV_IF = 13;
  /** RegularExpression Id. */
  int RSV_THEN = 14;
  /** RegularExpression Id. */
  int RSV_ELSE = 15;
  /** RegularExpression Id. */
  int RSV_WHILE = 16;
  /** RegularExpression Id. */
  int RSV_DO = 17;
  /** RegularExpression Id. */
  int RSV_READ = 18;
  /** RegularExpression Id. */
  int RSV_WRITE = 19;
  /** RegularExpression Id. */
  int RSV_VAR = 20;
  /** RegularExpression Id. */
  int TIPO = 21;
  /** RegularExpression Id. */
  int TIPO_INT = 22;
  /** RegularExpression Id. */
  int TIPO_BOOLEAN = 23;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_DIFERENCA = 24;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_IGUAL_IGUAL = 25;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_MENOR = 26;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_MENOR_IGUAL = 27;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_MAIOR_IGUAL = 28;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_MAIOR = 29;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_IGUALDADE = 30;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_AND = 31;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_OR = 32;
  /** RegularExpression Id. */
  int OPERADOR_LOGICO_NOT = 33;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_ATRIBUICAO = 34;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_ADICAO = 35;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_SUBTRACAO = 36;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_MULTIPLICACAO = 37;
  /** RegularExpression Id. */
  int OPERADOR_ARITMETICO_DIVISAO = 38;
  /** RegularExpression Id. */
  int PARENTESES_ESQ = 39;
  /** RegularExpression Id. */
  int PARENTESES_DIR = 40;
  /** RegularExpression Id. */
  int SIMBOLO_DOIS_PONTOS = 41;
  /** RegularExpression Id. */
  int SIMBOLO_VIRGULA = 42;
  /** RegularExpression Id. */
  int SIMBOLO_PONTO_E_VIRGULA = 43;
  /** RegularExpression Id. */
  int SIMBOLO_PONTO = 44;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 45;
  /** RegularExpression Id. */
  int IDENTIFICADOR_CHAMADA_PROCEDIMENTO = 46;
  /** RegularExpression Id. */
  int NUMERO_INTEIRO = 47;
  /** RegularExpression Id. */
  int LETRA = 48;
  /** RegularExpression Id. */
  int DIGITO = 49;
  /** RegularExpression Id. */
  int ERRO_COMENTARIO_MULT_LINHAS_SEM_FECHAR = 50;
  /** RegularExpression Id. */
  int ERRO_COMENTARIO_MULT_LINHAS_SEM_ABRIR = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMENTARIO_UMA_LINHA>",
    "<COMENTARIO_MULT_LINHAS>",
    "<COM>",
    "\"nova\"",
    "\"program\"",
    "\"procedure\"",
    "\"begin\"",
    "\"end\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"read\"",
    "\"write\"",
    "\"var\"",
    "<TIPO>",
    "\"int\"",
    "\"boolean\"",
    "\"<>\"",
    "\"==\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\">\"",
    "\"=\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\":=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"div\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\",\"",
    "\";\"",
    "\".\"",
    "<IDENTIFICADOR>",
    "<IDENTIFICADOR_CHAMADA_PROCEDIMENTO>",
    "<NUMERO_INTEIRO>",
    "<LETRA>",
    "<DIGITO>",
    "<ERRO_COMENTARIO_MULT_LINHAS_SEM_FECHAR>",
    "<ERRO_COMENTARIO_MULT_LINHAS_SEM_ABRIR>",
  };

}
